### ISSUE TITLE
Enhancement - image types

### ISSUE THREAD

**Issue by maceksimon** [scaleflex/js-cloudimage-responsive#10]
Hello and thanks for a great plugin!

I am looking for a way to serve webp images to my site through <picture> element and a set of <sources> would it be possible while using js-cloudimage-responsive?
If so, how would you go about it? Would you consider enabling this functionality through options?
Thanks!

Simon

**Comment by dzmitry-stramavus** [comment]
Hey @maceksimon , 

sorry for the late response, but I am not sure what you mean exactly. Can you give us more details?

**Comment by maceksimon** [comment]
Thanks for the answer, and sorry for the unclear formulation. I was just looking for a way to use WEBP images with your plugin on my website.
I have already solved the problem in a different way. However, in case someone else would be interested in this, would you be able to link to an example in docs?
Thanks!

**Comment by nganchev** [comment]
Hello @maceksimon 

If you are using the Cloudimage plugin, you should be using Cloudimage token as well, right?
In that case the image format delivery can be controlled from the Cloudimage admin and settings for the token itself.

Please refer to the documentation here https://docs.cloudimage.io/go/cloudimage-documentation-v7/en/image-compression 
There are settings inside the admin that can be used as well as using rules.

Also inside the plugin you can include parameters ( check the plugin ReadMe for "params" or "ci-params") for force_format with set value/s.
