### ISSUE TITLE
IE11 not wrapping image tag with div tags (with inline styles)

### ISSUE THREAD

**Issue by Jurjenvos** [scaleflex/js-cloudimage-responsive#13]
Hi, 

we're using js-cloudimage-responsive without a set aspect ratio, and it works great across modern browsers except in IE11. The image doesn't get wrapped with the correct div tags with inline styles  like it does in Chrome, Firefox or Safari, while it does set the image source on (lazy) load correctly.
 
It doesn't throw an error in the console though, which makes debugging hard. 

I was hoping I could get an answer here. Thanks in advance!

**Comment by dzmitry-stramavus** [comment]
hey @Jurjenvos , which version do you use ? blur-hash or low-preivew ?
