### ISSUE TITLE
2 suggestions: W3C validation + prevent enlargement

### ISSUE THREAD

**Issue by migliori** [scaleflex/js-cloudimage-responsive#14]
Hi,

I started to use the plugin and many features are really great, but I encounter 2 problems:

1. I wonder why you set the plugin to use **_ci-src_** instead of _**data-src**_
_**data-src**_ is validated with W3C but **_ci-src_** is not.
Is there a workaround? (it may be an idea to allow users to set their preference)

2. I couldn't find a way to keep the images within their original dimensions.
For example: I have a 750px wide image. I want it to be reduced on small screens, but I don't want it to be larger than 750px on large screens. By using the width and/or prevent_enlargement settings, the loaded image has the right dimensions, but the wrapper is 100% wide.
I haven't found a solution except to load the image directly from the Cloudimage URL without using ci_src, which is not ideal.
Is there a way?

Thank you for your answer

**Comment by dzmitry-stramavus** [comment]
hey @migliori ,

Implemented in 4.6.0

**Comment by dzmitry-stramavus** [comment]
about 2.

**Comment by Shackless** [comment]
Would it be possible to add a `data-*` variant for all your custom attributes on images like `ci-sizes`, `ci-ratio` etc.? Those still invalidate your HTML which could easily be avoided.

**Comment by dzmitry-stramavus** [comment]
hey @Shackless ,

Yes, to all params you can use data-* variant

**Comment by Shackless** [comment]
`data-ci-sizes` doesn't work while `ci-sizes` does.
