### ISSUE TITLE
Background-image problem

### ISSUE THREAD

**Issue by tigerchick** [scaleflex/js-cloudimage-responsive#15]
Using 4.6.0 (low quality image placeholder) version I can't seem to get CloudImage working as a background image as per your docs (ie. using: ci-bg-url="x.jpg")
It also doesn't appear to be working correctly in your example here: https://codesandbox.io/s/js-cloudimage-responsive-background-imxdm?file=/index.html
In your example I get a brief flash of the image before it disappears.
In my case I seem to get nothing.

**Comment by amrelbialy** [comment]
Thank you for reaching us , we will check the problem shortly . The fix will be available in the next release during the next 24 hours.

**Comment by dzmitry-stramavus** [comment]
@tigerchick , fixed

**available in 4.6.1**
