### ISSUE TITLE
if ci-src is left empty, error will occur and results in blocking failure

### ISSUE THREAD

**Issue by randallmlough** [scaleflex/js-cloudimage-responsive#2]
I noticed that if `ci-src` is passed an empty string value, it will fail and block all proceeding functions. In a perfect world we would always pass in a value for `ci-src`, but things happen. It would be helpful for the library to check for an empty string and either do nothing or return the users default 404 image.

**Comment by dzmitry-stramavus** [comment]
@randallmlough , hey 

thanks for opening the issue! Yes, totally agree. It will be implemented in next release

**Comment by dzmitry-stramavus** [comment]
@randallmlough , hey

**done in v2.2.0**
