### ISSUE TITLE
how to use when installed using npm?

### ISSUE THREAD

**Issue by Shackless** [scaleflex/js-cloudimage-responsive#20]
You mention in the README that the package can be added using npm but there is no further documentation on how to use it afterwards if you do. The module structure is pretty "uncommon" und does things like extending the global window object. There are no TypeScript types, defined default module or anything else that could help. I'm not even sure which modules I'd have to add when I peek at the /dist directory.

**Comment by amrw-js** [comment]
Hi @Shackless,
please check #23
