### ISSUE TITLE
Remove hardcoded `ci_info` query parameter to fix caching (max-age) issue

### ISSUE THREAD

**Issue by maczuk** [scaleflex/js-cloudimage-responsive#21]
Hi there,

Recently, I've spotted that images that are served using this library are not caching accordingly to settings in cloudimage admin panel:

**Admin Panel Configuration**
![image](https://user-images.githubusercontent.com/5550410/143767964-fa1b0927-7a12-4be0-a6e2-105a463c2720.png)

**How it looks like in the browser**
![image](https://user-images.githubusercontent.com/5550410/143768011-ae3e7c54-2d23-4620-8436-16125b16e644.png)

but if I remove `ci_info` parameter, the `max-age` is back to normal (as in the admin panel settings):
![image](https://user-images.githubusercontent.com/5550410/143768081-022ad604-0df5-4462-a9fd-bb6aaeb025c3.png)

So, the problem is with the `ci_info` query parameter that is embedded automatically to every image URL in source the code:
![image](https://user-images.githubusercontent.com/5550410/143768141-7520445f-3d96-4637-af46-b6724c60d588.png)

Can you remove this hardcoded part from the source code or add an option to disable it?

Thanks!

**Comment by nganchev** [comment]
Hello @maczuk and thanks for your report. 

The issue is resolved and pushed in the version **4.8.4 - 2021-01-04**
