### ISSUE TITLE
Using placeholder image breaks mobile calculation

### ISSUE THREAD

**Issue by TimTilroy** [scaleflex/js-cloudimage-responsive#4]
Hello,

We are using the plugin to load most of our images on both desktop and mobile. 
It's working great however we recently added a placeholder image of 1x1px to make sure no broken image shows during page load. 
This seems to have broken the calculation of the image width on mobile screens with a higher density. 
An example is visible on the frontpage of https://www.ava.be. On mobile the first image is very bad quality compared to how it was before. 

See these examples:
![cloudimage-responsive-bq](https://user-images.githubusercontent.com/38529879/60263396-d7ac4b80-98e0-11e9-87a6-a1d82d6fd292.JPG)
![cloudimage-responsive-gq](https://user-images.githubusercontent.com/38529879/60263398-d7ac4b80-98e0-11e9-91ea-b0fc95d519c7.JPG)

Any way we can fix this problem? 
We are using the latest version of the plugin (2.1.0). 

Regards

**Comment by dzmitry-stramavus** [comment]
@TimTilroy , hey

I'll check the issue during the week. Busy with launching another project

**Comment by dzmitry-stramavus** [comment]
@TimTilroy, hey

**fixed in v2.2.0**

**Comment by TimTilroy** [comment]
Thanks Dmitry!

We are upgrading the plugin in our next release. 

Regards
