### ISSUE TITLE
Background image doesn't load correctly in 3.3.1

### ISSUE THREAD

**Issue by josgerrits** [scaleflex/js-cloudimage-responsive#8]
If you check out https://codesandbox.io/s/js-cloudimage-responsive-background-joz41 you'll see what i mean. The image is stuck on "preview" mode and never correctly loads the right sized image.

**Comment by dzmitry-stramavus** [comment]
hey @josgerrits, thx for codesandbox link

I see the problem

it'll be fixed shortly

**Comment by dzmitry-stramavus** [comment]
**fixed in 3.3.3**

https://codesandbox.io/s/js-cloudimage-responsive-background-lkp0d

**Comment by josgerrits** [comment]
@dzmitry-stramavus  thanks for the quick fix :)
